language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
install:
    - "make install"
    - "mkdir var"
script:
    - prospector
    - ./run_tests.py --with-coverage --cover-package=dalite_xblock
notifications:
  email: false
addons:
  firefox: "36.0"